---
title: "Developer Notes"
---

### December 31, 2025

One reason that the `/data/` folder is in 
the `.gitignore` file is that 
s3 will be used for storing 
data, so it doesn't make sense
to exchange data back and forth between
the github and the local computer. Cookie cutter 
data science calls this idea
"separating the codebase from the 
data" <https://drivendata.co/blog/ccds-v2#data-storage>

Here are other key resources from today: 
<https://git-scm.com/docs/git-credential>
and <https://git-scm.com/docs/gitfaq#_credentials>. 
The latter link has the question: how do I specify my 
credentials when pushing over https?


### January 2, 2025

I am checking if Github Actions actually publishes and deploys my
website at the link: <https://williamclarktennis.github.io/MaierSteinSolverRepo/>.

Why is it not working? Please work!

### January 9, 2026

I did a simple example with Python logging to gain some
motivation for loguru, present in the 
`dataset.py` file and other files. 

See `https://docs.python.org/3/library/pathlib.html` to learn about
`PROJ_ROOT = Path(__file__).resolve().parents[1]`
in the `config.py` file.

I'm currently uncomfortable with the following files and items:

1. the `.env` file. It is currently empty. What other files
depend on it? I'm afraid I'll have to understand this file
before beginning development of source code.
2. The `Makefile`. Hopefully this file can be
ignored while I develop the source code.
3. The `pyproject.toml` file. I think this can 
be ignored while I develop source code. 
4. The `MaierSteinSolver/config.py` file. It 
says to load environment variables from the .env
file, but I don't know what those would be yet. 
5. The `dataset.py` file. When I want to develop source
code, should my code go into the main() function? I'm 
not sure how typer works, so I can't answer this question yet. 
Hopefully once I get a feeling for typer, then
I can start putting source code into the 
dataset.py file. 


For dot-env, look at: <https://pypi.org/project/python-dotenv/#getting-started>,
which is the python version.

When you try to run code using the MaierSteinSolver
package, you can't run it inside of
the MaierSteinSolver directory, or else you
will get a ModuleNotFoundError. 
So get in the practice of running scripts from the command
line from the root MaierSteinSolverRepo folder. 

I also consulted: 
<https://peps.python.org/pep-0518/>. 

So it turns out that the TOML file is needed
for making an `import MaierSteinSolver` statement work. 

Now I'm looking at pip documentation: 
<https://pip.pypa.io/en/stable/topics/local-project-installs/#editable-installs> 
because I want to install my own package (the MaierSteinSolver)
into my virtual environment. 

Here is a tutorial for the pyproject.toml file: <https://packaging.python.org/en/latest/guides/writing-pyproject-toml/>. 

I refactored the directory structure to include a src directory, 
which required changing the pyproject.toml. I still need to make corresponding
changes to the Makefile. 